# Generated by Django 6.0.1 on 2026-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Используется в адресе страницы',
                        max_length=255,
                        unique=True,
                        verbose_name='URL',
                    ),
                ),
                (
                    'preview',
                    models.TextField(
                        blank=True,
                        help_text='Используется в списке статей и для SEO',
                        verbose_name='Краткое описание',
                    ),
                ),
                ('content', models.TextField(verbose_name='Текст статьи')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Черновик'),
                            ('published', 'Опубликовано'),
                        ],
                        default='draft',
                        max_length=10,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
