# Generated by Django 6.0.1 on 2026-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Будет использоваться в hero-блоке и превью',
                null=True,
                upload_to='posts/',
                verbose_name='Главное изображение статьи',
            ),
        ),
    ]
