# Generated by Django 6.0.1 on 2026-01-09 11:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text='Вы можете вставлять текст, изображения, списки и ссылки',
                verbose_name='Текст статьи',
            ),
        ),
    ]
