# Generated by Django 6.0.1 on 2026-01-09 11:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name='Текст статьи'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(
                blank=True,
                help_text='Используется для превью и SEO',
                verbose_name='Краткое описание',
            ),
        ),
    ]
