# Generated by Django 6.0.1 on 2026-01-09 16:48

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, unique=True, verbose_name='name'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(blank=True, max_length=100, unique=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Используется в адресе страницы',
                max_length=255,
                unique=True,
                verbose_name='URL',
            ),
        ),
        migrations.CreateModel(
            name='CustomTaggedItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'object_id',
                    models.IntegerField(
                        db_index=True, verbose_name='object ID'
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_tagged_items',
                        to='contenttypes.contenttype',
                        verbose_name='content type',
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tagged_items',
                        to='blog.customtag',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='Теги для статьи',
                through='blog.CustomTaggedItem',
                to='blog.CustomTag',
                verbose_name='Tags',
            ),
        ),
    ]
