# Generated by Django 6.0.1 on 2026-01-09 17:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_customtag_alter_post_slug_customtaggeditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from='name',
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='posts/',
                verbose_name='Главное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(
                blank=True, verbose_name='Краткое описание'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                help_text='Автоматически генерируется из заголовка',
                populate_from='title',
                unique=True,
                verbose_name='URL',
            ),
        ),
    ]
