# Generated by Django 6.0.1 on 2026-01-09 17:15

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_customtag_slug_alter_post_image_and_more'),
        (
            'taggit',
            '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtaggeditem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='customtaggeditem',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='Теги для статьи',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
        migrations.DeleteModel(
            name='CustomTag',
        ),
        migrations.DeleteModel(
            name='CustomTaggedItem',
        ),
    ]
