# Generated by Django 6.0.1 on 2026-01-09 17:21

import autoslug.fields
from slugify import slugify

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_customtaggeditem_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                help_text='Автоматически генерируется из заголовка',
                populate_from='title',
                slugify=slugify,
                unique=True,
                verbose_name='URL',
            ),
        ),
    ]
