# Generated by Django 6.0.1 on 2026-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_options'),
        (
            'taggit',
            '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                upload_to='posts/', verbose_name='Главное изображение'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(
                choices=[('draft', 'Черновик'), ('published', 'Опубликовано')],
                db_index=True,
                default='draft',
                max_length=10,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(
                db_index=True, max_length=255, verbose_name='Заголовок'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(
                fields=['status', 'created_at'],
                name='blog_post_status_9deff2_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(
                fields=['post', 'created_at'],
                name='blog_postvi_post_id_2e6acd_idx',
            ),
        ),
    ]
