# Generated by Django 6.0.1 on 2026-01-12 14:00

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_created_at_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[blog.validators.validate_title],
                verbose_name='Заголовок',
            ),
        ),
    ]
