# Generated by Django 6.0.1 on 2026-01-12 15:48

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(
                db_index=True,
                max_length=150,
                validators=[blog.validators.validate_title],
                verbose_name='Заголовок',
            ),
        ),
    ]
