IMG_SRC_REGEX = r'<img [^>]*src="([^"]+)"'
MAX_LENGTH_STR = 50
MAX_LENGTH_SESSION_KEY = 40
DEFAULT_LENGTH_RELATED_POSTS = 3
DEFAULT_LENGTH_RECENT_POSTS = 3
MAX_LENGTH_TITLE = 150
MIN_LENGTH_TITLE = 3
STATUS_MAX_LENGTH = 10
